name: Create Github release

on:
  workflow_call:
    inputs:
      tag_name:
        required: false
        type: string

jobs:
  create-github-release:
    name: Create a Github release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ inputs.tag_name }}
