name: Create a Sentry release
on:
  workflow_call:
    inputs:
      target:
        required: false
        default: '16'
        type: string
      project:
        required: true
        type: string
jobs:
  create-sentry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.target }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Create a Sentry release
        uses: getsentry/action-release@v1.4.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ inputs.project }}
