name: Create a Sentry release

on:
  workflow_call:
    inputs:
      target:
        required: false
        default: '16'
        type: string
      package_manager:
        required: false
        default: 'yarn'
        type: string
      project:
        required: true
        type: string
      sourcemaps:
        required: false
        default: './dist'
        type: string

jobs:
  create-sentry-release:
    name: Create a Sentry release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        if: inputs.package_manager == 'bun'
        uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.target }}
          cache: ${{ inputs.package_manager == 'yarn' && 'yarn' || '' }}

      - name: Install dependencies
        run: ${{ inputs.package_manager }} install --frozen-lockfile

      - name: Build
        run: ${{ inputs.package_manager }} run build

      - name: Create a Sentry release
        uses: getsentry/action-release@v1.4.1
        with:
          sourcemaps: ${{ inputs.sourcemaps }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ inputs.project }}
