name: Publish NPM package

on:
  workflow_call:
    inputs:
      target:
        required: false
        default: '16'
        type: string
      package_manager:
        required: false
        default: 'yarn'
        type: string

jobs:
  publish-npm:
    name: Publish NPM package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        if: inputs.package_manager == 'bun'
        uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.target }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: ${{ inputs.package_manager }} install --frozen-lockfile

      - name: Publish to NPM
        run: ${{ inputs.package_manager }} publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
