name: Bump, tag, release and publish to npm

on: [workflow_call]

jobs:
  bump-version:
    uses: snapshot-labs/actions/.github/workflows/bump-version.yml@add-complete-release-workflow
    secrets: inherit

  create-github-release:
    uses: snapshot-labs/actions/.github/workflows/create-github-release.yml@add-complete-release-workflow
    if: startsWith(needs.bump-version.outputs.tag, 'v')
    needs: bump-version
    secrets: inherit
    with:
      tag_name: ${{ needs.bump-version.outputs.tag }}

  publish-npm:
    uses: snapshot-labs/actions/.github/workflows/publish-npm.yml@add-complete-release-workflow
    if: startsWith(needs.bump-version.outputs.tag, 'v')
    needs: [bump-version, create-github-release]
    secrets: inherit
