name: Test

on:
  workflow_call:
    inputs:
      target:
        required: false
        type: string
        default: '16'
      package_manager:
        required: false
        type: string
        default: 'yarn'
      mysql_database_name:
        required: false
        type: string
      mysql_schema_path:
        required: false
        type: string
        default: 'src/helpers/schema.sql'
      postgres_database_name:
        required: false
        type: string
      postgres_schema_path:
        required: false
        type: string
        default: 'src/helpers/schema.sql'
      redis:
        required: false
        type: boolean
        default: false
      redis_version:
        required: false
        type: string
        default: '7'
      dotenv_vars:
        required: false
        type: string
      working_directory:
        required: false
        type: string
        default: '.'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v7

      - name: Setup Bun
        if: inputs.package_manager == 'bun'
        uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.target }}
          cache: ${{ inputs.package_manager == 'yarn' && 'yarn' || '' }}

      - name: Set up MySQL
        if: ${{ inputs.mysql_database_name }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ inputs.mysql_database_name }};' -uroot -proot
          mysql -uroot -proot ${{ inputs.mysql_database_name }} < ${{ inputs.mysql_schema_path }}
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          mysql -uroot -proot -e "FLUSH PRIVILEGES;"

      - name: Set up PostgreSQL
        if: ${{ inputs.postgres_database_name }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
          sudo -u postgres createdb ${{ inputs.postgres_database_name }}
          sudo -u postgres psql -d ${{ inputs.postgres_database_name }} -f ${{ inputs.postgres_schema_path }}

      - name: Setup Redis
        if: ${{ inputs.redis }}
        run: docker run -d --name redis -p 6379:6379 redis:${{ inputs.redis_version }}

      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: ${{ inputs.package_manager }} install --frozen-lockfile

      - name: Setup test environment variables
        if: ${{ inputs.dotenv_vars }}
        working-directory: ${{ inputs.working_directory }}
        run: echo -e "\n${{ inputs.dotenv_vars }}" >> test/.env.test

      - name: Test
        working-directory: ${{ inputs.working_directory }}
        run: ${{ inputs.package_manager }} run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
